/**
 * Mock Books — Zoo Theme
 * Test data for Expo Go development. Used as fallback when Firestore is empty.
 */
import { Book } from '@types/book';

export const MOCK_ZOO_BOOKS: Book[] = [
  {
    id: 'mock-book-1',
    title: 'Leo the Lion',
    description:
      'Leo lives in the savanna and loves to roar! Follow Leo through a fun day at the zoo, where he meets new friends and learns to share.',
    coverUrl: 'https://placehold.co/300x400/ff5a1f/ffffff?text=Leo+%F0%9F%A6%81',
    audioFileUrl: '',
    price: 0,
    isFree: true,
    category: 'Animals',
    ageMin: 2,
    ageMax: 5,
    language: 'English',
    fileSize: 12 * 1024 * 1024,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    author: 'Zuupah Kids',
    pages: 24,
    rating: 4.8,
    reviews: 142,
    duration: 480,
  },
  {
    id: 'mock-book-2',
    title: 'Ella the Elephant',
    description:
      'Ella the elephant has the biggest ears in the whole zoo! She uses them to fan her friends on hot days. A story about kindness and friendship.',
    coverUrl: 'https://placehold.co/300x400/38b6c9/ffffff?text=Ella+%F0%9F%90%98',
    audioFileUrl: '',
    price: 0,
    isFree: true,
    category: 'Animals',
    ageMin: 2,
    ageMax: 6,
    language: 'English',
    fileSize: 14 * 1024 * 1024,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    author: 'Zuupah Kids',
    pages: 28,
    rating: 4.9,
    reviews: 203,
    duration: 540,
  },
  {
    id: 'mock-book-3',
    title: 'Zara the Zebra',
    description:
      'No two zebras have the same stripes — just like no two children are the same! Zara celebrates what makes everyone special.',
    coverUrl: 'https://placehold.co/300x400/2d3748/ffffff?text=Zara+%F0%9F%A6%93',
    audioFileUrl: '',
    price: 2.99,
    isFree: false,
    category: 'Animals',
    ageMin: 3,
    ageMax: 7,
    language: 'English',
    fileSize: 18 * 1024 * 1024,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    author: 'Zuupah Kids',
    pages: 32,
    rating: 4.7,
    reviews: 89,
    duration: 600,
  },
  {
    id: 'mock-book-4',
    title: 'Gigi the Giraffe',
    description:
      'Gigi can see the whole zoo from up high! She spots a lost baby penguin and goes on an adventure to help him find his family.',
    coverUrl: 'https://placehold.co/300x400/ffc400/333333?text=Gigi+%F0%9F%A6%92',
    audioFileUrl: '',
    price: 0,
    isFree: true,
    category: 'Adventure',
    ageMin: 3,
    ageMax: 6,
    language: 'English',
    fileSize: 16 * 1024 * 1024,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    author: 'Zuupah Kids',
    pages: 30,
    rating: 4.6,
    reviews: 117,
    duration: 570,
  },
  {
    id: 'mock-book-5',
    title: 'Pablo the Penguin',
    description:
      'Pablo lives in the cold section of the zoo but dreams of warmer adventures. He packs his tiny backpack and sets off to explore!',
    coverUrl: 'https://placehold.co/300x400/eef6f7/333333?text=Pablo+%F0%9F%90%A7',
    audioFileUrl: '',
    price: 1.99,
    isFree: false,
    category: 'Adventure',
    ageMin: 2,
    ageMax: 5,
    language: 'English',
    fileSize: 10 * 1024 * 1024,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    author: 'Zuupah Kids',
    pages: 22,
    rating: 4.5,
    reviews: 76,
    duration: 420,
  },
  {
    id: 'mock-book-6',
    title: 'Mia the Monkey',
    description:
      'Mia loves to count bananas, jump from tree to tree, and make the other animals laugh. A playful story that teaches counting 1 to 10.',
    coverUrl: 'https://placehold.co/300x400/ff5a1f/ffffff?text=Mia+%F0%9F%90%92',
    audioFileUrl: '',
    price: 0,
    isFree: true,
    category: 'Learning',
    ageMin: 2,
    ageMax: 5,
    language: 'English',
    fileSize: 11 * 1024 * 1024,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    author: 'Zuupah Kids',
    pages: 20,
    rating: 4.9,
    reviews: 258,
    duration: 390,
  },
];

export const getMockBookById = (id: string): Book | undefined =>
  MOCK_ZOO_BOOKS.find(b => b.id === id);
